name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: developer
          POSTGRES_PASSWORD: supersecretpassword
          POSTGRES_DB: forumapi_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGHOST: localhost
      PGUSER: developer
      PGDATABASE: forumapi_test
      PGPASSWORD: supersecretpassword
      PGPORT: 5432
      PGHOST_TEST: localhost
      PGUSER_TEST: developer
      PGDATABASE_TEST: forumapi_test
      PGPASSWORD_TEST: supersecretpassword
      PGPORT_TEST: 5432
      ACCESS_TOKEN_KEY: 8b7b4ef375716ab08b2a3951b29d52fc00b1c855f9d1a847229b8c5935bef56d9d271e76a9cf08e614300395c3b90ebe559cf968a0741b18c9505549394b2c70
      REFRESH_TOKEN_KEY: 5078605e074a462b1460608fcbe0d0963c644402e04ad334455ff5a856cb43fd99825861dde02957d5e3184c90c532ca7d0249df20fe93d535632f3d11be7bad
      ACCCESS_TOKEN_AGE: 3000

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js (v22 LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Create .test.env file
        run: |
          cp .env.example .test.env
          sed -i 's/PGDATABASE=forumapi/PGDATABASE=forumapi_test/g' .test.env

      - name: Run Code Linter
        run: npm run lint

      - name: Run Database Migrations for Test
        run: npm run migrate:test

      - name: Run Tests with Coverage
        run: npm run test:coverage
